all:get vendor install linter test run

get:
	curl https://glide.sh/get | sh
	go get -u github.com/kardianos/govendor
	go get -u gopkg.in/alecthomas/gometalinter.v2
	go get github.com/golang/mock/gomock
    go get github.com/golang/mock/mockgen

vendor:
	govendor sync update

install:
	gometalinter.v2 --install

linter:
	-gometalinter.v2 --vendor --tests --skip=mocks \
		--exclude='_gen.go' --exclude='docs.go' \
		--disable=gotype --disable=errcheck --disable=gas --disable=dupl \
		--deadline=1500s --checkstyle --sort=linter ./... > static-analysis.xml
test:
	-go test -v -cover ./... > tests.xml

build:
	go build -o gotoboox

run:
	go run main.go

