all:get vendor install linter test run

get:
	go get -u github.com/kardianos/govendor
	go get -u gopkg.in/alecthomas/gometalinter.v2

vendor:
	govendor sync update

install:
	gometalinter.v2 --install

linter:
	gometalinter --vendor --tests --skip=mocks \
		--exclude='_gen.go' --exclude='docs.go' \
		--disable=gotype --disable=errcheck --disable=gas --disable=dupl \
		--deadline=1500s --checkstyle --sort=linter ./... > static-analysis.xml
test:
	-go test -v -cover ./... > tests.xml

run:

	bash sys_variables.sh
	go run main.go

