// Code generated by MockGen. DO NOT EDIT.
// Source: bookRepo.go

// Package mock_repository is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	repository "github.com/metalscreame/GoToBoox/src/dataBase/repository"
	reflect "reflect"
)

// MockBookRepository is a mock of BookRepository interface
type MockBookRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBookRepositoryMockRecorder
}

// MockBookRepositoryMockRecorder is the mock recorder for MockBookRepository
type MockBookRepositoryMockRecorder struct {
	mock *MockBookRepository
}

// NewMockBookRepository creates a new mock instance
func NewMockBookRepository(ctrl *gomock.Controller) *MockBookRepository {
	mock := &MockBookRepository{ctrl: ctrl}
	mock.recorder = &MockBookRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockBookRepository) EXPECT() *MockBookRepositoryMockRecorder {
	return m.recorder
}

// GetAll mocks base method
func (m *MockBookRepository) GetAll() ([]repository.Book, error) {
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]repository.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll
func (mr *MockBookRepositoryMockRecorder) GetAll() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockBookRepository)(nil).GetAll))
}

// GetByCategory mocks base method
func (m *MockBookRepository) GetByCategory(categoryID int) ([]repository.Book, error) {
	ret := m.ctrl.Call(m, "GetByCategory", categoryID)
	ret0, _ := ret[0].([]repository.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCategory indicates an expected call of GetByCategory
func (mr *MockBookRepositoryMockRecorder) GetByCategory(categoryID interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCategory", reflect.TypeOf((*MockBookRepository)(nil).GetByCategory), categoryID)
}

// GetByID mocks base method
func (m *MockBookRepository) GetByID(bookID int) (repository.Book, error) {
	ret := m.ctrl.Call(m, "GetByID", bookID)
	ret0, _ := ret[0].(repository.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID
func (mr *MockBookRepositoryMockRecorder) GetByID(bookID interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBookRepository)(nil).GetByID), bookID)
}

// GetMostPopularBooks mocks base method
func (m *MockBookRepository) GetMostPopularBooks(id int) ([]repository.Book, error) {
	ret := m.ctrl.Call(m, "GetMostPopularBooks", id)
	ret0, _ := ret[0].([]repository.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMostPopularBooks indicates an expected call of GetMostPopularBooks
func (mr *MockBookRepositoryMockRecorder) GetMostPopularBooks(id interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMostPopularBooks", reflect.TypeOf((*MockBookRepository)(nil).GetMostPopularBooks), id)
}
