// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/metalscreame/gotoboox/src/dataBase/repository (interfaces: BookRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	repository "github.com/metalscreame/gotoboox/src/dataBase/repository"
	reflect "reflect"
)

// MockBookRepository is a mock of BookRepository interface
type MockBookRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBookRepositoryMockRecorder
}

// MockBookRepositoryMockRecorder is the mock recorder for MockBookRepository
type MockBookRepositoryMockRecorder struct {
	mock *MockBookRepository
}

// NewMockBookRepository creates a new mock instance
func NewMockBookRepository(ctrl *gomock.Controller) *MockBookRepository {
	mock := &MockBookRepository{ctrl: ctrl}
	mock.recorder = &MockBookRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockBookRepository) EXPECT() *MockBookRepositoryMockRecorder {
	return m.recorder
}

// GetAll mocks base method
func (m *MockBookRepository) GetAll() ([]repository.Book, error) {
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]repository.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll
func (mr *MockBookRepositoryMockRecorder) GetAll() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockBookRepository)(nil).GetAll))
}

// GetAllTakenBooks mocks base method
func (m *MockBookRepository) GetAllTakenBooks() ([]repository.Book, error) {
	ret := m.ctrl.Call(m, "GetAllTakenBooks")
	ret0, _ := ret[0].([]repository.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTakenBooks indicates an expected call of GetAllTakenBooks
func (mr *MockBookRepositoryMockRecorder) GetAllTakenBooks() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTakenBooks", reflect.TypeOf((*MockBookRepository)(nil).GetAllTakenBooks))
}

// GetByCategory mocks base method
func (m *MockBookRepository) GetByCategory(arg0 int) ([]repository.Book, error) {
	ret := m.ctrl.Call(m, "GetByCategory", arg0)
	ret0, _ := ret[0].([]repository.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCategory indicates an expected call of GetByCategory
func (mr *MockBookRepositoryMockRecorder) GetByCategory(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCategory", reflect.TypeOf((*MockBookRepository)(nil).GetByCategory), arg0)
}

// GetByID mocks base method
func (m *MockBookRepository) GetByID(arg0 int) (repository.Book, error) {
	ret := m.ctrl.Call(m, "GetByID", arg0)
	ret0, _ := ret[0].(repository.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID
func (mr *MockBookRepositoryMockRecorder) GetByID(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBookRepository)(nil).GetByID), arg0)
}

// GetMostPopularBooks mocks base method
func (m *MockBookRepository) GetMostPopularBooks(arg0 int) ([]repository.Book, error) {
	ret := m.ctrl.Call(m, "GetMostPopularBooks", arg0)
	ret0, _ := ret[0].([]repository.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMostPopularBooks indicates an expected call of GetMostPopularBooks
func (mr *MockBookRepositoryMockRecorder) GetMostPopularBooks(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMostPopularBooks", reflect.TypeOf((*MockBookRepository)(nil).GetMostPopularBooks), arg0)
}

// InsertNewBook mocks base method
func (m *MockBookRepository) InsertNewBook(arg0 repository.Book) error {
	ret := m.ctrl.Call(m, "InsertNewBook", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertNewBook indicates an expected call of InsertNewBook
func (mr *MockBookRepositoryMockRecorder) InsertNewBook(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertNewBook", reflect.TypeOf((*MockBookRepository)(nil).InsertNewBook), arg0)
}

// UpdateBookState mocks base method
func (m *MockBookRepository) UpdateBookState(arg0 int, arg1 string) error {
	ret := m.ctrl.Call(m, "UpdateBookState", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBookState indicates an expected call of UpdateBookState
func (mr *MockBookRepositoryMockRecorder) UpdateBookState(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBookState", reflect.TypeOf((*MockBookRepository)(nil).UpdateBookState), arg0, arg1)
}

// UpdateBookStateAndUsersBookIdByUserEmail mocks base method
func (m *MockBookRepository) UpdateBookStateAndUsersBookIdByUserEmail(arg0, arg1 string, arg2 int) error {
	ret := m.ctrl.Call(m, "UpdateBookStateAndUsersBookIdByUserEmail", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBookStateAndUsersBookIdByUserEmail indicates an expected call of UpdateBookStateAndUsersBookIdByUserEmail
func (mr *MockBookRepositoryMockRecorder) UpdateBookStateAndUsersBookIdByUserEmail(arg0, arg1, arg2 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBookStateAndUsersBookIdByUserEmail", reflect.TypeOf((*MockBookRepository)(nil).UpdateBookStateAndUsersBookIdByUserEmail), arg0, arg1, arg2)
}
